version: "3.8"

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: rumarkethubdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rumarkethub
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rumarkethubbackend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/rumarkethub
    depends_on:
      - db
    networks:
      - network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rumarkethubfrontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - network



volumes:
  db_data:

networks:
  network:
    driver: bridge